// Builds the Gemini request that generates SEO metadata + GEO (AI-citation)
// content for a product. Calls the Gemini API directly — no CLI subprocess,
// no OAuth session — so it runs headless anywhere (Docker, CI, etc.) with
// just GEMINI_API_KEY.
//
// schema_markup is deliberately NOT generated by the model — price,
// currency, availability, image, and canonical URL are already known
// exactly from the task packet, so scripts/seo-geo-worker.js assembles that
// object procedurally. The model only supplies the two fields that actually
// require judgment: brand and item_condition.
const { Type } = require('@google/genai');
const { chatModel } = require('../config/gemini');

const SYSTEM_INSTRUCTION = `You are an SEO/GEO specialist. Turn raw product data into structured SEO metadata and GEO (Generative Engine Optimization) content — the kind of factual, citation-ready content AI answer engines (ChatGPT, Perplexity, AI Overviews, Claude) can quote directly.

If a field in the input product data is missing, note it in "flags" and proceed with what's available — don't block on it. Never fabricate specs, prices, ratings, or availability not present in the input.

Step 1 — SEO metadata: meta_title (<=60 chars, primary keyword front-loaded), meta_description (<=160 chars, benefit + implicit CTA), og_title, og_description, image_alt_text (specific, not generic), url_slug, primary_keyword, secondary_keywords.

Step 2 — GEO content: definition_statement (1 sentence, factual, no fluff), key_facts (5-8 atomic claims that each stand alone if quoted out of context), faq (4-6 pairs, answer front-loaded, 2-4 sentences each), comparison_points (facts useful when an AI compares this product to alternatives).

Step 3 — brand and item_condition: infer the brand name from the product name/description if not explicit. Assume "NewCondition" unless the input clearly states otherwise.

Step 4 — Self-audit (mandatory): score your own Step 1-2 output 1-10 on factual_specificity, self_contained_clarity, answer_first_structure, and missing_info_completeness (does an AI assistant have what it needs to recommend this product?). If any score is below 7, revise that section once, then stop — flag remaining issues instead of endlessly retrying. Set status to "needs_review" if any score is still below 7 after your one revision pass, or if required input fields were missing; otherwise "ready".

Rules: no repetition across sections — a fact in key_facts should not be duplicated verbatim in faq answers or meta_description. Keep output minimal and dense — no marketing adjectives that don't carry factual weight.`;

const RESPONSE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    status: { type: Type.STRING, enum: ['ready', 'needs_review'] },
    brand: { type: Type.STRING },
    item_condition: { type: Type.STRING, enum: ['NewCondition', 'UsedCondition', 'RefurbishedCondition'] },
    seo: {
      type: Type.OBJECT,
      properties: {
        meta_title: { type: Type.STRING },
        meta_description: { type: Type.STRING },
        og_title: { type: Type.STRING },
        og_description: { type: Type.STRING },
        image_alt_text: { type: Type.STRING },
        url_slug: { type: Type.STRING },
        primary_keyword: { type: Type.STRING },
        secondary_keywords: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: [
        'meta_title',
        'meta_description',
        'og_title',
        'og_description',
        'image_alt_text',
        'url_slug',
        'primary_keyword',
        'secondary_keywords',
      ],
    },
    geo: {
      type: Type.OBJECT,
      properties: {
        definition_statement: { type: Type.STRING },
        key_facts: { type: Type.ARRAY, items: { type: Type.STRING } },
        faq: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: { q: { type: Type.STRING }, a: { type: Type.STRING } },
            required: ['q', 'a'],
          },
        },
        comparison_points: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: ['definition_statement', 'key_facts', 'faq', 'comparison_points'],
    },
    audit: {
      type: Type.OBJECT,
      properties: {
        scores: {
          type: Type.OBJECT,
          properties: {
            factual_specificity: { type: Type.INTEGER },
            self_contained_clarity: { type: Type.INTEGER },
            answer_first_structure: { type: Type.INTEGER },
            missing_info_completeness: { type: Type.INTEGER },
          },
          required: [
            'factual_specificity',
            'self_contained_clarity',
            'answer_first_structure',
            'missing_info_completeness',
          ],
        },
        issues: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: ['scores', 'issues'],
    },
    flags: { type: Type.ARRAY, items: { type: Type.STRING } },
  },
  required: ['status', 'brand', 'item_condition', 'seo', 'geo', 'audit', 'flags'],
};

function buildRequest(taskPacket) {
  return {
    model: chatModel,
    contents: [{ role: 'user', parts: [{ text: `Product data:\n${JSON.stringify(taskPacket)}` }] }],
    config: {
      systemInstruction: SYSTEM_INSTRUCTION,
      responseMimeType: 'application/json',
      responseSchema: RESPONSE_SCHEMA,
      maxOutputTokens: 4096,
      temperature: 0.3,
      // See assistantPrompt.service.js — gemini-2.5-flash's dynamic
      // "thinking" can silently consume the whole maxOutputTokens budget
      // before producing output. Not needed for direct structured JSON.
      thinkingConfig: { thinkingBudget: 0 },
    },
  };
}

module.exports = { buildRequest };
