/**
 * product_seo — SEO metadata + GEO (AI-citation) content generated by the
 * seo-geo-agent subagent for each product. `status` doubles as the work
 * queue: rows land as 'pending' on product create/update, and
 * scripts/seo-geo-worker.js polls for 'pending' rows, invokes the agent,
 * and updates the row in place. See productSeoSync.service.js for the
 * enqueue side and seo-geo-worker.js for the processing side.
 */
exports.up = function up(knex) {
  return knex.schema.createTable('product_seo', (table) => {
    table.charset('utf8mb4');
    table.collate('utf8mb4_unicode_ci');

    table.increments('id').unsigned().primary();
    table.integer('product_id').unsigned().notNullable();
    table.string('status', 20).notNullable().defaultTo('pending');
    // pending | processing | ready | needs_review | failed
    table.integer('attempts').unsigned().notNullable().defaultTo(0);
    table.string('source_hash', 64).nullable();
    table.json('seo').nullable();
    table.json('geo').nullable();
    table.json('schema_markup').nullable();
    table.json('audit').nullable();
    table.json('flags').nullable();
    table.text('last_error').nullable();
    table.datetime('created_at').notNullable();
    table.datetime('updated_at').notNullable();

    table.unique(['product_id']);
    table.index(['status']);

    table
      .foreign('product_id')
      .references('products.id')
      .onDelete('CASCADE');
  });
};

exports.down = function down(knex) {
  return knex.schema.dropTableIfExists('product_seo');
};
